version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build: ./
    ports:
      - '9000:9000'
    depends_on:
      - mongo
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
        - '27017:27017'

# no persist for now